from PyQt6.QtWidgets import QMainWindow, QApplication
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 220)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 113))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.color_group_1Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.color_group_1Layout.setContentsMargins(0, 0, 0, 0)
        self.color_group_1Layout.setObjectName("color_group_1Layout")
        self.color_group_1 = QtWidgets.QButtonGroup(self.centralwidget)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.color_group_1Layout.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.color_group_1Layout.addWidget(self.radioButton)
        self.color_group_1.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.color_group_1Layout.addWidget(self.radioButton_2)
        self.color_group_1.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.color_group_1Layout.addWidget(self.radioButton_3)
        self.color_group_1.addButton(self.radioButton_3)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 0, 160, 113))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.color_group_2Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.color_group_2Layout.setContentsMargins(0, 0, 0, 0)
        self.color_group_2Layout.setObjectName("color_group_2Layout")
        self.color_group_2 = QtWidgets.QButtonGroup(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.color_group_2Layout.addWidget(self.label_2)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.color_group_2Layout.addWidget(self.radioButton_4)
        self.color_group_2.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.color_group_2Layout.addWidget(self.radioButton_5)
        self.color_group_2.addButton(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.color_group_2Layout.addWidget(self.radioButton_6)
        self.color_group_2.addButton(self.radioButton_6)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(320, 0, 160, 113))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.color_group_3Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.color_group_3Layout.setContentsMargins(0, 0, 0, 0)
        self.color_group_3Layout.setObjectName("color_group_3Layout")
        self.color_group_3 = QtWidgets.QButtonGroup(self.centralwidget)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.color_group_3Layout.addWidget(self.label_3)
        self.radioButton_7 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.color_group_3Layout.addWidget(self.radioButton_7)
        self.color_group_3.addButton(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.color_group_3Layout.addWidget(self.radioButton_8)
        self.color_group_3.addButton(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.color_group_3Layout.addWidget(self.radioButton_9)
        self.color_group_3.addButton(self.radioButton_9)
        self.make_flag = QtWidgets.QPushButton(parent=self.centralwidget)
        self.make_flag.setGeometry(QtCore.QRect(350, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.make_flag.setFont(font)
        self.make_flag.setObjectName("make_flag")
        self.result = QtWidgets.QLabel("", parent=self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 120, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.result.setFont(font)
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Текстовый флаг"))
        self.label.setText(_translate("MainWindow", "Цвет №1"))
        self.radioButton.setText(_translate("MainWindow", "Синий"))
        self.radioButton_2.setText(_translate("MainWindow", "Красный"))
        self.radioButton_3.setText(_translate("MainWindow", "Зелёный"))
        self.label_2.setText(_translate("MainWindow", "Цвет №2"))
        self.radioButton_4.setText(_translate("MainWindow", "Синий"))
        self.radioButton_5.setText(_translate("MainWindow", "Красный"))
        self.radioButton_6.setText(_translate("MainWindow", "Зелёный"))
        self.label_3.setText(_translate("MainWindow", "Цвет №3"))
        self.radioButton_7.setText(_translate("MainWindow", "Синий"))
        self.radioButton_8.setText(_translate("MainWindow", "Красный"))
        self.radioButton_9.setText(_translate("MainWindow", "Зелёный"))
        self.make_flag.setText(_translate("MainWindow", "Сделать флаг"))


class FlagMaker(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.make_flag.clicked.connect(self.make_flag_c)
        self.setFixedSize(self.width(), self.height())

    def make_flag_c(self):
        color = [group.checkedButton().text() for group in [self.color_group_1, self.color_group_2, self.color_group_3]]
        self.result.setText(f"Цвета: {color[0]}, {color[1]} и {color[2]}")


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    ex = FlagMaker()
    ex.show()
    sys.exit(app.exec())